config:
  - wait_cost: 0.5
    wait_time: 5
    safety_time: 20
    gate_delay_time: [0]
    gate_delay_prob: [1]
    runway_delay_time: [0]
    runway_delay_prob: [1]
    safety_distance: 500
    tick_per_time_unit: 1
    strict_passing_order: 0
    schedule_time_window: 600
