language: python
os:
  - "linux"
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - cd data/real-west-all-terminals
  - python generate_scenario.py
  - python generate.py
  - cd ../..
script:
  - travis_wait python -m unittest discover tests
