---
name: base
airport: simple
batch: null

simulator:
  # Real seconds passed between each tick
  pause_time: 0
  # Enable for test mode
  test_mode: false
  # Enable scenario regeneration
  scenario_regeneration: true
  # Number of simulation runs with one same setting (only works in batch mode)
  times: 1
  # Enable the simulator continue to try until it reaches the required `times`
  # (only works in batch mode)
  try_until_success: true

simulation:
  # Seconds between each simulation epoch
  time_unit: 30
  # Seconds between each reschedule
  reschedule_cycle: 120
  # Feet required between two nodes (otherwise, we see two nodes as the same)
  close_node_threshold: 30
  # Feet required when calculating whether a node belongs to a link
  close_node_link_threshold: 20
  # Enable or disable cache for shortest routes
  cache: true
  # Separation requirement in feet between two aircraft
  separation: 50
  # End time of a day (it's okay if we don't finish scheduling all the
  # aircraft if we're not using the makespan metric)
  end_time: "9:00"

uncertainty:
  # Enable or disable the uncertain in simulation
  enabled: false
  # Probability of an aircraft holds at node unexpectedly (depends on time_unit)
  prob_hold: 0.05
  # Number of ticks of each delay added
  ticks_hold: 5
  # Enable or disable uncertainty at gate
  at_gate: false
  # Enable or disable uncertainty at spot position
  at_spot: true
  # Enable or disable uncertainty at runway start
  at_runway: false

scheduler:
  # Name of the scheduler file under the `scheduler` folder
  name: deterministic_scheduler
  # Maximum number of attempts on trying to resolve a conflict
  max_resolve_conflict_attempt: 10

logger:
  # Options are: critical, error, warning, info, debug, notset
  level: debug
  # Enable logging into a file instead of stdout/stderr
  file: false
