name: base
airport: simple
batch: null

simulator:
  # Real seconds passed between each tick
  pause_time: 0
  # Enable for test mode
  test_mode: false

simulation:
  # Seconds between each simulation epoch
  time_unit: 30
  # Seconds between each reschedule
  reschedule_cycle: 900
  # Feets required between two nodes (otherwise, we seem two nodes as the same)
  close_node_threshold: 30
  # Feets required when calculating whether a node is belong a link
  close_node_link_threshold: 20
  # Enable or disable cache for shortest routes
  cache: true
  # Separation requirement in feets between two aircrafts
  separation: 50

monitor:
  # Enable or disable the real-time monitor
  enabled: false

uncertainty:
  # Enable or disable the uncertain in simulation
  enabled: false
  # Probability of an aircraft holds at node unexpectedly (depends on time_unit)
  prob_hold: 0.2
  # Seconds of the mean of an unexpected hold at node
  hold_time_mean: 120
  # Seconds of the standard deviation of an unexpected hold at node
  hold_time_deviation: 60

scheduler:
  # Name of the scheduler file under the `scheduler` folder
  name: deterministic_scheduler
  # Minimum tightness at each node in schedule
  tightness: 180
  # Velocity of an moving aircraft used for distance calculation (ft/sec)
  aircraft_velocity: 5
  # Future time period that the scheduler solves the conflicts (sec)
  resolve_conflicts_time: 600
  # Maximum number of attempts on trying to resolve a conflict
  max_resolve_conflict_attempt: 10

logger:
  # Options are: critical, error, warning, info, debug, notset
  level: debug
  # Enable logging into a file instead of stdout/stderr
  file: false
