config:
  - wait_cost: 0.5
    wait_time: 5
    safety_time: 20
    gate_delay_time: [0, 1, 2, 3, 4, 5, 6]
    gate_delay_prob: [0.8, 0.16, 0.032, 0.0064, 0.00128, 0.000256, 0.000064]
    runway_delay_time: [0, 1, 2, 3, 4, 5, 6]
    runway_delay_prob: [0.8, 0.16, 0.032, 0.0064, 0.00128, 0.000256, 0.000064]
    safety_distance: 500
    tick_per_time_unit: 1
    strict_passing_order: 0  