config:
  - wait_cost: 0.5
    wait_time: 5
    safety_time: 20
    gate_delay_time: [0, 10, 20, 30, 40]
    gate_delay_prob: [0.3, 0.5, 0.1, 0.05, 0.05]
    runway_delay_time: [0, 10]
    runway_delay_prob: [0.7, 0.3]
    safety_distance: 500
    tick_per_time_unit: 1
    strict_passing_order: 0
    schedule_time_window: 300
